config/routes.rb
YYWeb::Application.routes.draw do
  
  resources :post do
    post :set_top, :on => :member
    post :set_sticky, :on => :member
    post :cancel_top, :on => :member
    post :cancel_sticky, :on => :member
  end
  
  resources :comment
  
  resources :paragraph do
    get :single, :on => :member
  end
  
  resources :comment_praise
  
  resources :post_praise
  resources :post_attention

  resources :translated_text
  resources :translated_text_vote
  
  resources :notification
  
  get 'user/loginpage' => 'user#login_page'
  get 'user/registerpage' => 'user#register_page'
  
  post 'user/login' => 'user#login'
  post 'user/register' => 'user#register'
  get 'user/logout' => 'user#logout'
  
  get 'setting/personal' => 'setting#show_personal'
  get 'setting/icon' => 'setting#show_icon'
  
  post 'setting/personal' => 'setting#update_personal'
  post 'setting/upload_icon' => 'setting#upload_icon'
  
  get 'node/:id(/page/:page)(/:path_name)' => 'node#show',
      :as => 'post_list',
      :constraints => {:id => /\d+/, :page => /\d+/ }
  root :to => 'root#show'
  
  get 'util/redirect' => 'util#handle_redirect'
  
end

app/models/post.rb
#!/bin/env ruby
# encoding: utf-8

class Post < ActiveRecord::Base

  TopicType = 1
  TranslationType =2
  
  NormalState = 1
  DeleteState = 2
  
  NoHonorPost = 400
  StickyPost = 300
  TopPost = 200
  StickyAndTopPost = 100
  
  ColumnsExceptContent = Post.column_names - ["content"]
  
  has_many :paragraphs, :order => 'paragraphs.idx'
  has_many :comments, :order => 'comments.create_at'
  
  belongs_to :author, :foreign_key => :author_id, :class_name => "User"
  belongs_to :node, :foreign_key => :node_id, :class_name => "Node"
  belongs_to :last_reply_user, :foreign_key => :last_reply_user_id, :class_name => "User"
  
  validates :title, :presence => true,
                   :length => {:minimum => 1, :maximum => 120}
  validates :content, :length => {:minimum => 0, :maximum => 2000}
  
  # 用 include 语句将所有paragraphs的translated_texts一次性载入。
  # 但是这样 rails 就不做缓存了，对于热贴的效率可能还不如用N条Selete语句载入快。（因为Rails会缓存。）
  def load_paragraphs
    ps = self.paragraphs
    text_ids = []
    ps.each do |p|
      text_ids << p.translated_text_id
    end
    TranslatedText.where("translated_texts.id in (#{text_ids.join(",")})").all.each do |tt|
      for i in 0..(self.paragraphs.length)
        break if self.paragraphs[i].translated_text_id == tt.id
      end
      self.paragraphs[i].choosed_text = tt
    end
    return ps
  end
  
  def is_top?
    return honor_state == TopPost || honor_state == StickyAndTopPost
  end
  
  def is_sticky?
    return honor_state == StickyPost || honor_state == StickyAndTopPost
  end
  
  def set_top=(value)
    if value
      self.honor_state = Post::TopPost if self.honor_state == Post::NoHonorPost
      self.honor_state = Post::StickyAndTopPost if self.honor_state == Post::StickyPost
    else
      self.honor_state = Post::NoHonorPost if self.honor_state == Post::TopPost
      self.honor_state = Post::StickyPost if self.honor_state == Post::StickyAndTopPost
    end
  end
  
  def set_sticky=(value)
    if value
      self.honor_state = Post::StickyPost if self.honor_state == Post::NoHonorPost
      self.honor_state = Post::StickyAndTopPost if self.honor_state == Post::TopPost
    else
      self.honor_state = Post::NoHonorPost if self.honor_state == Post::StickyPost
      self.honor_state = Post::TopPost if self.honor_state == Post::StickyAndTopPost
    end
  end
  
  def can_reply?
    return true
  end
                   
  def can_delete_by? (user)
    (not user.nil?) && self.node.can_manager_by?(user)
  end
  
  def can_edit_by? (user)
    return false if user.nil?
    if self.node.can_manager_by?(user)
      return true
    elsif (not user.nil?) and user.id == self.author.id
      return true
    else
      return false
    end
  end
  
  def can_top_by? (user)
    (not user.nil?) && user.belongs_to_managers?
  end
  
  def can_sticky_by? (user)
    (not user.nil?) && self.node.can_manager_by?(user)
  end
  
  def has_delete?
    return false
  end
  
  def attention_id_by(user)
    return nil if user.nil?
    pa = PostAttention.where(:user_id => user.id, :post_id => self.id).first
    if pa.nil?
      return nil
    else
      return pa.id
    end
  end
  
  def praise_id_by(user)
    return nil if user.nil?
    pp = PostPraise.where(:user_id => user.id, :post_id => self.id).first
    if pp.nil?
      return nil
    else
      return pp.id
    end
  end
  
end

app/controllers/post_controller.rb
class PostController < ApplicationController

  def show
    @post = Post.find_by_id(params[:id].to_i)
    raise ActionController::RoutingError.new('Post Not Found') unless @post
    
    if @post.is_delete
      raise ActionController::RoutingError.new('Post Deleted')
    end
    @page_title = @post.title
    @author = @post.author
    @content = @post.content.split(/\n/)
    
    @attention_id = @post.attention_id_by(curr_user)
    @praise_id = @post.praise_id_by(curr_user)
    @can_reply = can_reply?(@post)
    
    @paragraphs = @post.paragraphs
    
    page = params[:page].to_i
    page = page == 0 ? 1 : page
    @comments = @post.comments.page(page).per_page(Comment::PerPage)
    @comment_page = page
  end
  
  def new
    @edit = false
    @node = Node.find_by_id(params[:node].to_i)
    @type = params[:type].to_i
    check_node_and_type(@node, @type)
    render :'post/editor'
  end
  
  def edit
    post = Post.find_by_id(params[:id].to_i)
    raise ActionController::RoutingError.new('Post Not Found') if post.nil?
    
    @title = post.title
    @content = post.content
    
    @node = post.node
    @edit = true
    @post_id = post.id
    @type = post.post_type
    check_node_and_type(@node, @type)
    render :'post/editor'
  end
  
  def create
    node = Node.find_by_id(params[:node].to_i)
    type = params[:type].to_i
    check_node_and_type(node, type)
    raise ActionController::RoutingError.new('Can Not Post.') unless node.can_post_by?(curr_user)
    
    if type == Post::TranslationType
      paragraphs = params[:paragraphs]
      if paragraphs.length == 0
        return render :text => "error"
      end
    end
    
    users = []
    content = handle_user_input(params[:content]) do |name, user|
      users << user
    end
    
    post = Post.new
    post.author = curr_user
    post.node = node
    post.create_at = Time.now
    post.update_at = Time.now
    post.post_type = type
    post.state = Post::NormalState
    post.is_elite = false
    post.title = params[:title]
    post.content = content
    post.last_reply_user = curr_user
    post.last_reply_at = Time.now
    
    if type == Post::TranslationType
      idx = 0
      paragraphs.each do |p|
        p = p.strip
        if /^>>>>>+[^><]*<<<<<+$/.match(p).nil?
          paragraph = Paragraph.new(:paragraph_type => Paragraph::TypeContent)
        else
          cut = /[^><]+/.match(p)
          p = (cut.nil?) ? "" : cut[0].strip
          if p.empty?
            paragraph = Paragraph.new(:paragraph_type => Paragraph::TypeLine)
            p = "#line"
          else
            paragraph = Paragraph.new(:paragraph_type => Paragraph::TypeTitle)
          end
        end
        paragraph.source_text = p
        paragraph.idx = idx
        post.paragraphs << paragraph
        idx += 1
      end
    end
    
    if not post.save
      return render :text => "error"
    end
    
    users.each do |user|
      NotificationMessage.notify(user, curr_user, post, NotificationMessage::TypePostAt)
    end
    
    PostAttention.create(
      :user_id => curr_user.id,
      :post_id => post.id,
      :create_at => Time.now,
      :last_watch_time => Time.now
    )
    
    render :text => post.id.to_s
  end
  
  def update
    post = Post.find_by_id(params[:id].to_i)
    if post.nil?
      render :text => "error"
      return
    end
    if not post.can_edit_by?(curr_user)
      render :text => "error"
      return
    end
    post.title = params[:title]
    post.content = params[:content]
    post.last_reply_user = curr_user
    post.last_reply_at Time.now
    post.save
    
    render :text => "ok"
  end
  
  def destroy
    post = Post.find_by_id(params[:id].to_i)
    if post.nil?
      render :text => "error"
      return
    end
    
    if not post.can_delete_by?(curr_user)
      render :text => "error"
      return
    end
    
    post.is_delete = true
    post.save
    
    render :text => "ok"
  end
  
  def set_top
    post = Post.find_by_id(params[:id].to_i)
    
    if post.nil?
      render :text => "error"
      return
    end
    
    if not post.can_top_by?(curr_user)
      render :text => "error"
      return
    end
    
    post.set_top = true    
    post.save
    render :text => "ok"
    
  end
  
  def cancel_top
    post = Post.find_by_id(params[:id].to_i)
    
    if post.nil?
      render :text => "error"
      return
    end
    
    if not post.can_top_by?(curr_user)
      render :text => "error"
      return
    end
    
    post.set_top = false
    post.save
    render :text => "ok"
    
  end
  
  def set_sticky
    post = Post.find_by_id(params[:id].to_i)
    
    if post.nil?
      render :text => "error"
      return
    end
    
    if not post.can_sticky_by?(curr_user)
      render :text => "error"
      return
    end
    
    post.set_sticky = true
    post.save
    render :text => "ok"
    
  end
  
  def cancel_sticky
    post = Post.find_by_id(params[:id].to_i)
    
    if post.nil?
      render :text => "error"
      return
    end
    
    if not post.can_sticky_by?(curr_user)
      render :text => "error"
      return
    end
    
    post.set_sticky = false
    post.save
    render :text => "ok"
    
  end
  
  private 
  
  def check_node_and_type(node, type)
    if node.nil?
      raise ActionController::RoutingError.new('Node Not Found')
    elsif type != Post::TopicType and type != Post::TranslationType
      raise ActionController::RoutingError.new('Error Type')
    end
  end
  
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/editor.html.erb
<% content_for :head do %>
  <link href="/stylesheet/commit.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript">
    var postId = <%= @post_id || "null" %>;
    var isEdit = <%= @edit %>;
    var nodeId = <%= @node.id %>;
    var type = <%= @type %>;
  </script>
  <%= javascript_include_tag "app/editor" %>
<% end %>
		<div id="navigation">
		  <a href="/">首页</a>
		  <span> >> </span>
		  <%= link_to @node.name, node_path(@node) %> 
		  <span> >> </span>
		  <% if @edit %>编辑<% else %>发贴<% end %>
		</div>
		
		<div class="title">
		  <% if @type == Post::TranslationType %>
		    <% if @edit %>编辑翻译贴<% else %>申请翻译<% end %>
		  <% elsif @type == Post::TopicType %>
		    <% if @edit %>编辑主题<% else %>发表主题<% end %>
		  <% end %>
		</div>
		<div class="fill-box">
			<span>标题：<br/></span>
			<input id="title" type="text" <% if not @title.blank? %>value="<%= @title %>"<% end %>/>
		</div>
		<div class="fill-box">
			<span>
			  <% if @type == Post::TranslationType %>想说的话：
			  <% elsif @type == Post::TopicType %>主题内容：
			  <% end %>
			<br/></span>
			<% if @content.nil? %>
			<textarea id="post-content" class="textarea-notify" spellcheck="false">
			  <% if @type == Post::TranslationType %>
			  本文的引荐辞、或自己的感想，或仅仅是单纯的想说点什么。
			  <% else %>主题内容，请文明用语。
			  <% end %>
			</textarea>
			<% else %>
			<textarea id="post-content" spellcheck="false"><%= @content %></textarea>
			<% end %>
			<% if @type == Post::TopicType and (not @edit)%>
			<div class="button">
				<a href="#" id="commit-topic">发表主题</a>
			</div>
			<% end %>
		</div>
		<% if @type == Post::TranslationType and (not @edit) %>
		<div id="translation-box" class="fill-box">
			<span>申请翻译的原文：<br/></span>
			<textarea id="source-text" class="textarea-notify" spellcheck="false">不应包含特殊符号、分割线、个人感想、翻译后的中文</textarea>
			<div class="button">
				<a id="btn-split-article" href="#">原文分段</a>
			</div>
  	</div>
  	<% end %>
  	<% if @edit %>
  	<div class="button">
		  <a id="btn-edit" href="#">提交编辑</a>
	  </div>
	  <% end %>

app/views/post/show.html.erb
<% content_for :head do %>
  <link href="/stylesheet/post.css" rel="stylesheet" type="text/css" />
  <%= javascript_include_tag "app/postshow" %>
  <%= javascript_include_tag "app/postattentionpraise" %>
  <%= javascript_include_tag "app/comment" %>
<% end %>
  <script type="text/javascript">
    var attentionId = <%= @attention_id || "null" %>;
    var praiseId = <%= @praise_id || "null" %>;
    var postId = <%= @post.id %>;
    var commentPage = <%= @comment_page %>;
    var hasUserLogin = <%= not curr_user.nil? %>;
    var nodePath = "<%= node_path(@post.node) %>";
  </script>
  
		<div id="add-area">
			<div id="post-operation">
		  <% if not curr_user.nil? %>
				<% if @attention_id.nil? %>
				<a id="btn-attention" href="#" title="贴子有新评论和译文后将提醒你">
				<div class="operation">
				<span id="txt-attention">关注</span>
				<% else %>
				<a id="btn-attention" href="#" title="取消关注后与此贴相关的更新将不会提新你">
				<div class="operation-cancel">
				<span id="txt-attention">取消关注</span>
				<% end %>
				  <span class="operation-count">(<span id="count-attention"><%= @post.attentions_count %></span>)</span>
				</div>
				</a>
				<% if @praise_id.nil? %>
				<a id="btn-praise" href="#" title="给TA一个赞">
				<div class="operation">
				<span id="txt-praise">赞</span>
				<% else %>
				<a id="btn-praise" href="#" title="你已赞过该贴，点击取消赞。">
				<div class="operation-cancel">
				<span id="txt-praise">取消赞</span>
				<% end %>
					<span class="operation-count">(<span id="count-praise"><%= @post.praises_count %></span>)</span>
				</div>
				</a>
			<% end %>
			</div>
			<div class="label">
				<div class="label-title">主题相关</div>
				<div class="label-content">
					<div>
					  <% if @post.post_type == Post::TranslationType %>
		        翻译贴；
		        <% elsif @post.post_type == Post::TopicType %>
		        主题贴；
		        <% end %>
					  <% if @post.is_elite %>精华贴;<% end %>
					</div>
					<div>关注人数：<%= @post.attentions_count %></div>
					<div>评论：<%= @post.comments_count %></div>
					<div>赞人数：<%= @post.praises_count %></div>
					<div>发表时间：<%= formate_date(@post.create_at) %>(<%= time_to_now(@post.create_at) %>前)</div>
					<div>最后评论/翻译时间：<%= formate_date(@post.last_reply_at) %>(<%= time_to_now(@post.last_reply_at) %>前)</div>
				</div>
			</div>
			
			<div class="label">
			  <div class="label-title">推荐阅读</div>
			  <nav class="label-content">
			  <% @post.node.posts_list.limit(6).each do |p| %>
			    <div><%= link_to p.title, post_path(p), :title => p.title, :target => '_blank' %></div>
			  <% end %>
			  </nav>
			</div>
		</div>
		<div id="main-area">
			<nav id="navigation">
				<a href="/">首页</a>
				<span> >> </span>
				<%= link_to @post.node.name, node_path(@post.node) %> 
				<span> >> 贴子正文</span>
			</nav>
			<!-- 作者信息 -->
			<div id="author" class="piece">
				<div class="proposer">翻译申请人</div>
				<img id="author-icon" src="<%= @author.icon_url %>" />
				<div id="author-info">
					<div id="author-head">
						<%= @author.name %>
					</div>
					<div id="author-autograph">
						<%= @author.signature %>
					</div>
				</div>
				<div style="clear:both;"></div>
			</div>
			<!-- 正文 -->
			<div id="post-body" class="piece">
				<h1 class="title" style="text-align: center;"><%= @post.title %></h1>
				<div class="content">
					<% @content.each do |line| %>
					  <p><%=raw line %></p>
					<% end %>
					<div style="text-align: right">
						<% if @post.can_delete_by?(curr_user) %>
						  <a href="#" id="btn-delete-post">[删除]</a>
						<% end %>
						
						<% if @post.can_top_by?(curr_user) %>
						  <% unless @post.is_top? %>
						  <a href="#" id="btn-set-top">[置首]</a>
						  <% else %>
						  <a href="#" id="btn-cancel-top">[取消置首]</a>
						  <% end %>
						<% end %>
						
						<% if @post.can_sticky_by?(curr_user) %>
						  <% unless @post.is_sticky? %>
						  <a href="#" id="btn-set-sticky">[精华]</a>
						  <% else %>
						  <a href="#" id="btn-cancel-sticky">[取消精华]</a>
						  <% end %>
						<% end %>
						
						<% if @post.can_edit_by?(curr_user) %>
						  <%= link_to '[编辑]', edit_post_path(@post), :class => 'inside-button' %>
						<% end %>
						<span><%= formate_date(@post.create_at) %></span>
					</div>
				</div>
			</div>
			<!-- 段落 -->
			<% if @post.post_type == Post::TranslationType %>
			<div id="paragraphs">
			<% @paragraphs.each do |p| %>
			<% case p.paragraph_type %>
			<% when Paragraph::TypeContent %>
			  <div id="p-<%= p.id %>" class="paragraph">
			    <% @p = p %>
			    <%= render :partial => '/paragraph/single-show' %>
			  </div>
			<% when Paragraph::TypeTitle %>
			  <div class="title"><%= p.source_text %></div>
			<% when Paragraph::TypeLine %>
			  <div class="line"></div>
			<% end %>
			<% end %>
            
            <div class="notify-text">
			  	<p>翻译不够精确？翻译有错误？如果你对某一段翻译不满意，请掏出你的键盘，把你自己的翻译提交上去吧。</p>
				<p>知言译义网鼓励大家贡献自己的翻译。哪怕是只言片语，也欢迎。</p>
			</div>
            
			</div>
			<% end %>
			
			<!-- 评论 -->
			<div class="title">评论</div>
			<div id="comment-containers">正在载入评论...</div>
			
			<!-- 发表评论 -->
			<% if @can_reply %>
			<div id="commit-comment">
				<div>发表评论：</div>
				<textarea id="comment-content" class="textarea-notify" spellcheck="false">输入你的评论，字数不得超过500字。</textarea>
			</div>
			<div class="p-button">
				<a href="#" id="btn-commit-comment">提交</a>
			</div>
			<% else %>
			<div id="commit-comment">
			  <div>只有登录后，且没有被禁言的用户才可以评论。</div>
			</div>
			<% end %>